OldSneerJaw/synctos

README.md
etc/prepare-tests.sh
etc/sync-function-template.js
package.json
test/array-spec.js
test/resources/array-doc-definitions.js
test/resources/string-doc-definitions.js
test/sample-sync-doc-definitions-spec.js
test/string-spec.js

Allows finer-grained control of the lengths of these data types beyond the existing `mustNotBeEmpty` parameter. Also added new unit test classes to perform more systematic validation of the sync function maker script's output instead of only testing the output of the sample document definitions, which were created for specific real-world use cases.

Add minimumLength and maximumLength validation to arrays and strings

---

README.md
etc/prepare-tests.sh
etc/sync-function-template.js
test/array-spec.js
test/date-spec.js
test/datetime-spec.js
test/resources/date-doc-definitions.js
test/resources/datetime-doc-definitions.js
test/string-spec.js

For pure `date`s, the validation logic is quite simple: since the type requires that values are of a fixed length and format, they can be compared alphanumerically as strings. However, for `datetimes`, it gets more complicated because time and time zone components are optional and a value's time zone may not match the time zone defined in the validator. The solution I chose was to construct `Date` objects from the input value and the validator range value and then compare their Unix timestamp values.
Note that I have not yet verified these validation parameters in a live Sync Gateway instance. As such, there may be some inconsistencies in date handling that are not yet apparent.

Minimum and maximum value validation for date and datetime types

---

etc/sync-function-template.js
test/sample-sync-doc-definitions-spec.js

Previously, if the old instance of a document was deleted, when creating a new document to replace it, the authorization method required that the user had the replacement channel(s). However, it is more logical to expect the creation channel(s), so that's what it does now.

Treat replacement of a deleted doc as doc creation when authorizing

---

README.md
etc/prepare-tests.sh
etc/sync-function-template.js
package.json
samples/sample-sync-doc-definitions.js
test/immutable-spec.js
test/resources/immutable-doc-definitions.js
test/sample-sync-doc-definitions-spec.js

Array, object and hashtable type items may now be marked as `immutable` to ensure they are not changed when a document is replaced. The constraint is applied recursively so that it can be applied to complex types with an arbitrary number of nested layers and to items that have themselves been nested an arbitrary number of layers deep.
Tests were successfully executed with `npm test`.

Support the immutable constraint for complex data types

---

make-sync-function

Fixes issue #6.
The output file was written to the correct path. However, the directory in which the make-sync-function script resides was incorrectly prepended to the output file's path when displaying the success message. Now it simply displays the raw output filename.

Issue #6: Display the correct output filename in maker script

---

README.md
etc/sync-function-template.js
samples/sample-sync-doc-definitions.js
test/resources/array-doc-definitions.js
test/resources/date-doc-definitions.js
test/resources/datetime-doc-definitions.js
test/resources/immutable-docs-doc-definitions.js
test/resources/immutable-items-doc-definitions.js
test/resources/string-doc-definitions.js

This is a more natural and concise way to define property validators since each can be thought of as an entry that is uniquely identified by its property name (just like properties in an object/hashtable). Since it is a breaking change, the package version will be bumped up from 0.1.x to 0.2.x.

Define doc and object property validators in an object/hash instead of an array

---

etc/test-helper.js
samples/sample-sync-doc-definitions.js
test/general-spec.js
test/sample-sync-doc-definitions-spec.js

Backported the most recent changes to the sample sync document definitions from the `business-sync` bucket's document definitions and then modified the corresponding specs to use the test helper module that was introduced in #10. This completes the transition to test helper for all specs.
Also addressed some comments from #10.

Apply the test helper to the sample document definitions

---

package.json

Specify caret ranges for each of the npm dev dependencies to protect against automatic upgrades with breaking changes.

Restrict versions of npm dev dependencies

---

etc/prepare-tests.sh
package.json

When running the project's specs (e.g. `npm test`), also execute JSHint on the generated sync functions to identify lint and fail the operation if any is found.

Use JSHint to check for lint in generated sync functions

---

etc/test-helper.js

Because each of a document definition's expected channels can be defined as either an array of strings or a string, the test helper now performs some normalization to ensure that tests don't need to care whether the access mode's channel was declared as an array with one element or as a string.

Ensure test helper handles channel access with only one channel

---

etc/sync-function-template.js
etc/test-helper.js
make-sync-function

The make-sync-function script now returns an exit status of 1 if an error was encountered when generating a sync function.
Resolves issue #36.

Issue #36: Non-zero exit status on sync function generator failure

---

CHANGELOG.md
README.md
etc/sync-function-template.js
etc/validation-error-message-formatter.js
test/date-spec.js
test/range-constraint-spec.js
test/range-constraint-specs.js
test/resources/range-constraint-doc-definitions.js

Added new range validation constraints `minimumValueExclusive` and `maximumValueExclusive` for use with `integer`, `float`, `date` and `datetime` validation types. They are similar to `minimumValue` and `maximumValue`, respectively, except that they do not allow values that are equal to the specified range limit value.
Addresses issue #32.

Issue #32: Option to exclude min/max values in range validation constraints

---

CHANGELOG.md

Switched the "Unreleased" section to "v1.2.0" in preparation for publishing to npm.

Update change log for release of v1.2.0

---

.jshintrc
etc/.jshintrc
etc/sync-function-template.js
test/.jshintrc

Explicitly declares JSHint configuration files so that JSHint rules are enforced consistently on JavaScript code regardless of execution environment. More info on the JSHint options configured herein: http://jshint.com/docs/options/
Addresses issue #49.

Issue #49: JSHint configuration files

---

CHANGELOG.md
README.md
etc/sync-function-template.js
etc/test-helper.js
samples/sample-sync-doc-definitions.js
test/access-assignment-spec.js
test/resources/access-assignment-doc-definitions.js
test/sample-sync-doc-definitions-spec.js

Introduces a mechanism to configure in the document definition which channels should be dynamically assigned to users and/or roles as a document of that type is created, replaced or deleted. The configuration is flexible enough to allow either static (i.e. predefined lists of users/roles/channels) or dynamic (i.e. functions that return computed lists of users/roles/channels) assignment. Also extends the corresponding test-helper module validation functions so that callers can write specs that verify the channels that are assigned to users and roles.
Addresses issue #24.

Issue #24: Allow assignment of channels to users and roles

---

CHANGELOG.md
README.md
package.json

Upgrades jshint, mocha and simple-mock to their most recent versions to take advantage of bug fixes and the latest features in each. There are currently no updates to expect.js, however. Also includes minor improvements to documentation in the README.
Addresses issue #52.

Issue #52: Upgrade npm development dependencies

---

CHANGELOG.md
README.md
etc/sync-function-template.js
etc/test-helper.js
samples/sample-sync-doc-definitions.js
test/authorization-spec.js
test/channel-assignment-spec.js
test/general-spec.js
test/resources/authorization-doc-definitions.js
test/sample-sync-doc-definitions-spec.js

Allows document definitions to explicitly specify which users have access to which operation types (add, replace or remove) via an additional top-level document definition property: `authorizedUsers`. Uses the same format as the `channels` and `authorizedRoles` properties. When used in combination with either or both of those properties, allows the user to specify that authorization will be granted if the user has at least one of the authorized channels, roles and/or usernames for the corresponding operation type. Changes are backward compatible.
Addresses issue #23.

Issue #23: Authorization by username

---

etc/sync-function-template.js
etc/test-helper.js

Fixes an edge case where it is not possible to add, replace and/or remove a document via the Sync Gateway admin API if its document definition does not specify any authorization methods (channels, roles or users) for the corresponding operation type. By design, requests via the admin API should **always** be authorized to create, replace or remove documents.
Addresses an issue introduced with the implementations of #22 & #23.

Issues #22 & #23: Allow admin API to create documents with no authorization methods

---

README.md
etc/sync-function-template.js
test/access-assignment-spec.js
test/custom-actions-spec.js
test/general-spec.js
test/resources/custom-actions-doc-definitions.js

Adds support for an additional function parameter passed to custom actions that specifies, depending on the event, the document type ID and definition, the authorization that was applied for the operation, the channel access that was assigned to users/roles and the channels that were assigned to the document. Also allows for custom metadata to be passed from one custom action to another. Refer to the updated README for more info.
With this PR and #62, issue #25 should be fully addressed.

Issue #25: Custom action metadata parameter

---

.jshintrc
CHANGELOG.md
README.md
etc/.jshintrc
etc/sync-function-template.js
etc/test-helper.js
test/.jshintrc
test/access-assignment-spec.js
test/resources/access-assignment-doc-definitions.js

Adds a new type of access assignment that dynamically assigns roles to users by way of the standard sync function API's `role` function. Complementary to the channel access assignment feature that was introduced for #24 (Support dynamic assignment of channels to roles and users).
Addresses issue #61.

Issue 61: Assign role access to users

---

CHANGELOG.md

This is the final step before the package is published to npm.
Note the "Unreleased" section will be restored to the change log after the release is published.
Also, I added a link to the commits for v1.0.0 to the change log.

Update change log for release of v1.5.0

---

CHANGELOG.md
README.md
etc/sync-function-template.js

Provides a convenient shorthand for determining whether a document is missing/non-existant (i.e. `null` or `undefined`) or deleted (i.e. its `_deleted` property is `true`): `isDocumentMissingOrDeleted`. Documented in the README, along with the `isValueNullOrUndefined` helper function.
Addresses issue #69.

Issue 69: Helper function to determine if a document is missing or deleted

---

CHANGELOG.md
README.md
etc/sync-function-template.js
test/resources/type-id-validator-doc-definitions.js
test/type-id-validator-spec.js

Adds a predefined property validator called `typeIdValidator` that is meant to be applied to a document property that specifies its document's type (typically the `type` property). It should come in handy when used in combination with the simple type filter (i.e. `simpleTypeFilter`).
Addresses issue #72.

Issue 72: Type identifier property validator

---

CHANGELOG.md

This is the final step before the package is published to npm.
Note that the "Unreleased" section will be restored to the change log after the release is published.

Update change log for release of v1.6.0

---

CHANGELOG.md
README.md
etc/sync-function-template.js
test/resources/simple-type-filter-doc-definitions.js
test/simple-type-filter-spec.js

The simple type filter (`simpleTypeFilter`) is a convenience that specifies that a document's type is defined by the value of its "type" property. For the sake of convenience, if a document definition uses a `simpleTypeFilter` but does not explicitly include a property validator for a "type" property, automatically allow the "type" property at the document root and validate it with the built in `typeIdValidator` (as implemented in #74).
Addresses issue #73.

Issue 73: Implicitly allow type property when using the simple type filter

---

CHANGELOG.md
README.md
etc/sync-function-template.js
etc/validation-error-message-formatter.js
test/enum-spec.js
test/resources/enum-doc-definitions.js

An enum property validation type specifies a predefined list of valid values. For its document to be considered valid, a value assigned to a property of this type must belong to the predefined values list.
Addresses issue #78.

Issue 78: New property validation type for enums

---

CHANGELOG.md
README.md
etc/sync-function-template.js
etc/validation-error-message-formatter.js
test/hashtable-spec.js
test/resources/hashtable-doc-definitions.js

Allows a document definition to declare the minimum and maximum number of elements that a hashtable may hold.
Addresses issue #79.

Issue 79: Hashtable size constraints

---

etc/test-helper.js

Moves the export statements and function documentation to the top of the test-helper module to help developers discover the functionality available.
Addresses issue #88.

Issue #88: Reorganize test-helper exports and documentation

---

CHANGELOG.md

Includes all previously unreleased additions and changes. The "Unreleased" section of the change log will be restored in another commit following the release.
This is the final step before the release of v1.8.0.

Update change log for release of v1.8.0

---

CHANGELOG.md
README.md
etc/sync-function-validation-module.js
test/immutable-items-spec.js
test/resources/immutable-items-doc-definitions.js

Includes support for setting item validation constraints (e.g. `mustNotBeEmpty`, `required`, `immutable`, etc.) dynamically, via a function, in addition to the existing "static" method. While functionally complete, this should be considered a work in progress; a series of future pull requests will gradually increase test coverage for all of the validation constraints that are affected.
The first step in addressing issue #94.

Issue 94: Initial implementation of dynamic item validation constraints

---

test/array-spec.js
test/hashtable-spec.js
test/immutable-when-set-spec.js
test/resources/array-doc-definitions.js
test/resources/hashtable-doc-definitions.js
test/resources/immutable-when-set-doc-definitions.js
test/resources/string-doc-definitions.js
test/string-spec.js

Follows PR #96 to introduce test cases for additional property/element/key constraints (specifically `immutableWhenSet` and `mustNotBeEmpty`). I strongly recommend viewing the changes with `?w=1` to make it more manageable.
Part 2 of addressing issue #94. Several additional PRs full of test cases will follow this one.

Issue 94: Dynamic item constraint tests - round 1

---

etc/sync-function-validation-module.js
test/dynamic-constraints-spec.js
test/general-spec.js
test/resources/array-doc-definitions.js
test/resources/dynamic-constraints-doc-definitions.js
test/resources/enum-doc-definitions.js
test/resources/general-doc-definitions.js
test/resources/hashtable-doc-definitions.js
test/resources/immutable-items-doc-definitions.js
test/resources/immutable-when-set-doc-definitions.js
test/resources/range-constraint-doc-definitions.js
test/resources/required-doc-definitions.js
test/resources/string-doc-definitions.js

Follows pull request #104 to add the following changes:
* Dynamic resolution of the property/element `type` field so that validation type can be specified as a function.
* Changes the order of parameters in the constraint function from `value`, `oldValue`, `doc`, `oldDoc` to `doc`, `oldDoc`, `value`, `oldValue`. Putting `doc` and `oldDoc` first ensures consistency with other functions that accept these parameters.
* Pass an old document that has been deleted (i.e. `oldDoc`'s `_deleted` property is `true`) as `null` in calls to the constraint function so that an implementer doesn't have to include special handling for that case.
* Added general-purpose test cases for dynamic item constraint validation.
Part 5 of addressing issue #94. A few more PRs full of test cases should follow.

Issue 94: Improvements to dynamic item constraints

---

CHANGELOG.md
etc/sync-function-template.js
etc/sync-function-validation-module.js
samples/fragment-payment-processor-settlement.js
test/immutable-docs-spec.js
test/property-validators-spec.js
test/resources/immutable-docs-doc-definitions.js
test/resources/property-validators-doc-definitions.js

Constraints that are specified at the document level (e.g. `allowAttachments`, `immutable`, `propertyValidators`) may now be specified dynamically as a function. This initial pull request includes test cases for `allowUnknownProperties`, `propertyValidators`, `immutable`, `cannotReplace` and `cannotDelete`.
The first of two pull requests to address issue #97.

Issue 97: Implementation of dynamic document constraint validation

---

README.md
etc/sync-function-validation-module.js
test/attachment-constraints-spec.js
test/resources/attachment-constraints-doc-definitions.js

Follows pull request #109 to complete the implementation of issue #97. Changes include:
* Test cases for dynamic attachment properties: `allowAttachments`, `attachmentConstraints`, etc.
* Documentation of dynamic document-level constraint properties
I believe that one would be best served to view this PR's changes with `?w=1`.

Issue 97: More test cases and documentation for dynamic document constraints

---

CHANGELOG.md
etc/sync-function-loader.js
etc/test-helper.js
package.json
test/hashtable-spec.js
test/resources/hashtable-doc-definitions.js
test/resources/string-doc-definitions.js
test/string-spec.js

To avoid syntax errors when a generated sync function is inserted as a multiline string in a Sync Gateway configuration file, all backtick characters that appear in the sync function are now automatically escaped.
I also manually verified that, with this fix, Sync Gateway accepts a sync function generated from document definitions that contain backtick characters.
Addresses issue #113.

Issue 113: Escape backticks in generated sync functions

---

CHANGELOG.md
README.md
etc/sync-function-validation-module.js
samples/fragment-business.js
samples/fragment-notification-transport-processing-summary.js
samples/fragment-notification-transport.js
samples/fragment-notification.js
samples/fragment-notifications-config.js
samples/fragment-notifications-reference.js
samples/fragment-payment-attempt.js
samples/fragment-payment-processor-definition.js
samples/fragment-payment-processor-settlement.js
samples/fragment-payment-requisition.js
samples/fragment-payment-requisitions-reference.js
samples/sample-sync-doc-definitions.js
test/sample-notifications-config-spec.js
test/sample-payment-processor-definition-spec.js

Previously, sync functions generated by synctos could not be loaded by the [Sync Gateway admin UI](https://github.com/couchbaselabs/sync_gateway_admin_ui)'s editor view due to a [defect](https://github.com/couchbaselabs/sync_gateway_admin_ui/issues/47) in the way that project injects a sync function's contents into the page. Specifically, the admin UI uses the version of the JavaScript `String.replace` function that allows special replacement patterns in the replacement value, one of which (`$'`) appears frequently at the end of a number of regular expressions in synctos' templates. A proper fix requires the underlying issue to be resolved in that project; however, as an immediate workaround to the problem, double quotes are now used instead of single quotes when constructing such regular …

Issue #116: Avoid character sequences used as special replacement patterns

---

test/must-equal-spec.js
test/resources/must-equal-doc-definitions.js

Defined some additional test cases to verify that the `mustEqual` constraint is enforced when set via an `arrayElementsValidator` or `hashtableValuesValidator`.
Addresses issue #110.

Issue 110: Test that mustEqual constraint applies to array and hashtable elements

---

etc/sync-function-loader.js
etc/test-helper-environment-template.js
etc/test-helper.js
test/sync-function-loader-spec.js

The test-helper module now uses Node.js' built in `vm.runInThisContext` to evaluate a sync function's contents in the current V8 virtual machine context as a cleaner and more reliable way to parse JavaScript overall than using `eval` directly.
Also removed the sync-function-loader module's dependency on the built in "path" module since every Node.js module has an implicit `__dirname` variable that makes its use of `path.dirname` superfluous.

Issue 43: Use V8 context to parse sync functions in test-helper module

---

etc/prepare-tests.sh
src/document-definitions-shell-maker.js
src/document-definitions-validator.js
src/templates/document-definitions-shell-template.js
test/authorization-spec.js
test/document-definitions-shell-maker-spec.js
test/resources/authorization-doc-definitions.js
validate-document-definitions

To avoid environment mismatches that occur when mixing objects from two different contexts, create document definitions shells in the current Node.js virtual machine context instead of in a new context. Otherwise string comparisons with `===` and use of the `instanceof` keyword do not produce the expected results.
Also took the opportunity to update the `npm test` script to run the document definitions validator utility on each of the sample document definitions and test document definitions to help ensure these examples conform to specification. As a result the `noAuthorizationsDefinedDoc` type was removed from the document definitions for the authorization specifications since it is, by definition, an invalid document definition (i.e. it does not define `channels`, `authorizedRoles` or …

Issue 43: Load document definitions shells in the current VM context

---

src/document-definitions-shell-maker.js
src/document-definitions-validator.js
test/document-definitions-validator-spec.js

Defines specifications for validation of the "essential" document definition properties:
* `typeFilter`
* `propertyValidators`
* `channels`
* `authorizedRoles`
* `authorizedUsers`
Also expands the validation that is applied to those and other properties.
This is just one of a number of upcoming pull requests to address issue #43.

Issue 43: Test cases for validation of essential document definition properties

---

src/document-definitions-validator.js
test/document-definitions-validator-advanced-spec.js
test/document-definitions-validator-essentials-spec.js
test/document-definitions-validator-spec.js

The previous pull request (#140) introduced test cases for validation of the "essential" document-level properties of a document definition (`typeFilter`, `channels`, `authorizedRoles`, `authorizedUsers`, `propertyValidators`). This pull request adds test cases for all remaining "advanced" properties.
Future pull requests will add full validation of a document definition's `propertyValidators` as part of issue #43.

Issue 43: Test cases for validation of advanced document-level properties

---

src/document-definitions-validator.js
test/document-definitions-validator-advanced-spec.js
test/document-definitions-validator-essentials-spec.js

Comprised of two notable changes:
* Validate that the `view` operation is not supported for `authorizedRoles` and `authorizedUsers`
* Check for superfluous channel, role and user authorizations when the document is immutable
Furthers the implementation of issue #43. More work to be done though.

Issue 43: Expand validation of document authorization

---

src/document-definition-properties-validator.js
src/document-definitions-validator.js
src/templates/document-definitions-shell-template.js
test/document-definition-properties-validator-spec.js
test/document-definitions-validator-advanced-spec.js
test/document-definitions-validator-essentials-spec.js

Introduces a new module that will perform validation on property validator definitions. The initial implementation simply wires it into the document-definitions-validator module and performs simple validation of each property's validation type.
Additional pull requests to come to address issue #43.

Issue 43: Validation of document definition property validator types

---

README.md

Adds badges for latest npm package version and the status of the package's dependencies to the README. Also removes the Greenkeeper badge since it is largely redundant.
Addresses issue #144.

Issue 144: Update README badges

---

.travis.yml
CHANGELOG.md
etc/sync-function-authorization-module.js
test/authorization-spec.js
test/resources/authorization-doc-definitions.js

Prevents cases where a user is mistakenly permitted to perform a replace or remove operation when they have the necessary channel, role or username to perform add operations but the document type does not explicitly declare corresponding permissions for replace and/or remove operations.
Addresses issue #149.
Note: this pull request does not target the `master` branch because I intend to issue the update as a patch release without all of the in-progress work on document validation that is currently on the `master` branch. Instead, the release will be cut from the `v1.9.2-dev` branch, which is based off of the `v1.9.1` tag, and then that branch will be merged into `master`.

Issue 149: Ensure add permissions are only valid for add operations

---

CHANGELOG.md
etc/sync-function-validation-module.js
test/immutable-nested-properties-spec.js
test/resources/immutable-nested-properties-doc-definitions.js

This bug erroneously rejected cases where a new object could not be added to an array for an existing document if the document definition specifies that one or more properties of the object are immutable. Also applied to hashtables with immutable values nested in an array.
Addresses issue #152.
Note: this pull request does not target the master branch because I intend to issue the update as a patch release without all of the in-progress work on document validation that is currently on the `master` branch. Instead, the release will be cut from the `v1.9.3-dev` branch, which is based off of the `v1.9.2` tag, and then that branch will be merged into `master`.

Issue 152: Allow objects with immutable properties to be added to an array

---

.travis.yml
package.json

In order to upgrade to the newest version of mocha, support for Node.js 0.10.x has to be removed from the Travis CI build configuration. This should not be a problem since that version of Node.js is positively ancient and there is no need to be able to build the project with it anymore. Furthermore, this is not a breaking change for those packages that depend on synctos because mocha is only a development dependency.
Replaces PR #151.

Update mocha to version 4.0.1 

---

.travis.yml
package-lock.json

Includes an npm lockfile for tracking dependency versions. Also updates the Travis CI build configuration to include Greenkeeper's support for [npm lockfiles](https://github.com/greenkeeperio/greenkeeper-lockfile#npm) so that it can continue to keep the project's dependencies up to date as well.

Add an npm lockfile

---

CHANGELOG.md
etc/test-helper.js
package.json
test/access-assignment-spec.js
test/attachment-constraints-spec.js
test/custom-actions-spec.js
test/general-spec.js
test/init-spec.js
test/sample-notification-transport-spec.js
test/type-id-validator-spec.js

As it turns out, there were a few more API incompatibilities than I initially expected, but it wasn't too bad in the end.  
We gain richer feedback in assertion failures, as both substitute APIs support failure messages on all matchers, but lose elegant and/or flexible handling of `throws` conditions.  
The Node assert API rejects objects thrown that are not `Error`s and Chai simply doesn't support a custom function for asserting the Error.  Trusty old try-fail/catch-assert pattern was used to overcome these weaknesses.

Issue #157 chai upgrade

---

CHANGELOG.md
etc/sync-function-template.js
etc/test-helper.js
test/array-spec.js
test/authorization-spec.js
test/custom-actions-spec.js
test/general-spec.js
test/hashtable-spec.js
test/immutable-docs-spec.js
test/immutable-items-spec.js
test/required-spec.js
test/sample-business-spec.js
test/sample-notification-transport-processing-summary-spec.js
test/sample-payment-attempt-spec.js
test/sample-payment-processor-settlement-spec.js
test/simple-type-filter-spec.js

To accommodate the special case wherein a Couchbase SDK client deletes a document in a [shared access bucket](https://developer.couchbase.com/documentation/mobile/current/guides/sync-gateway/shared-bucket-access.html), the sync function now allows documents that do not exist/have already been deleted to be deleted freely, even if the sync function can't determine the document's type. This should be safe since the document that is being deleted does not exist anymore/at all.
Also replaced all uses of the `undefined` global variable with `void 0`. This is the preferred means to get an undefined value in code since the global `undefined` variable can be reassigned ([more info](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void)).
Addresses issue #160.

Issue 160: Allow Couchbase SDK to delete documents in a shared access bucket

---

CONTRIBUTING.md

A relatively tiny change. Should definitely be the last one to address issue #174, for real this time.

Issue 174: Add reference to main package module in contribution guidelines

---

test/attachment-constraints.spec.js
test/custom-actions.spec.js
test/general.spec.js
test/init.spec.js

Ensure that, when a test case expects that the sync function will throw an error but no error is encountered, the resulting test failure message will be relevant.
It may be helpful to view the diffs with `?w=1`.

Improve handling of expected errors in test cases

---

.gitignore
.nycrc
CONTRIBUTING.md
package-lock.json
package.json
src/document-definition-properties-validator.spec.js
src/document-definitions-shell-maker.js
src/document-definitions-shell-maker.spec.js
src/file-fragment-loader.spec.js
src/test-environment-maker.js
src/test-helper.js
src/test-helper.spec.js
src/validation-error-formatter.js
src/validation-error-formatter.spec.js
test/authorization.spec.js

The project's `test` process now generates a code coverage report for files in the `src` directory with a minimum of 95% coverage of statements and branches and 100% coverage of functions. As part of this effort, I had to improve test coverage of several modules to meet those thresholds. A future goal is to achieve 100% coverage of statements and branches and to increase the thresholds accordingly (i.e. require 100% coverage across the board).
The diff size may appear very large, but don't let it scare you; ~75% of the changes come from `package-lock.json` due to the addition of the [nyc](https://www.npmjs.com/package/nyc) development dependency for generating code coverage reports. The bulk of the changes that were not automatically generated can be found in the new `test-helper.spec.js` …

Issue 181: Code coverage configuration

---

CHANGELOG.md
etc/jshintrc-sync-function-template.json
templates/.jshintrc
templates/document-definitions-shell-template.js
templates/json-stringify-module.js
templates/sync-function-template.js
templates/sync-function-validation-module.js

Previously the `mustEqual` and `mustEqualStrict` constraints used `JSON.stringify` when formatting an error message indicating a constraint violation; however, since the JavaScript engine used by Sync Gateway does not support the JSON object, this resulted in JavaScript errors at runtime if a client tried to store a document with a value that violated the constraint. Removed references to the JSON object from the sync function templates and replaced it with a polyfill (`json-stringify-module.js`) that replicates the behaviour of `JSON.stringify`.
Addresses issue #190.

Issue 190: Remove reference to JSON object from generated sync functions

---

README.md
package.json

Documented `jsonStringify` in the project's README so that it can be used by, e.g., `customValidation`s. Also added the keyword "validation" to the package configuration.
Final piece of the puzzle for issue #190.

Issue 190: Document the JSON stringify function in the README

---

CHANGELOG.md
templates/sync-function-validation-module.js

Use [Date.parse](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse) to ensure the sync function will not accept a date or datetime value it cannot represent.
Addresses issue #199.

Issue 199: Allow only dates that can be parsed by Date.parse

---

.jshintignore

Prevents JSHint from generating warnings/errors for directories that should not be linted (e.g. `build/coverage`, `lib`, `node_modules`).

Exclude additional directories from JSHint

---

README.md

Each section references the other to increase the chances that a user will discover the full testing and validation capabilities of the project.

Issue #43: Reference the validation utility from the testing section of the README and vice versa

---

CHANGELOG.md
src/testing/test-helper.js
src/testing/test-helper.spec.js
templates/sync-function-validation-module.js
test/general.spec.js

During execution of a sync function ignore any document property key that starts with an underscore if it is at the top level of the document. Sync Gateway does not allow top-level document property keys to start with an underscore because it reserves that notation to indicate internal document properties.
Addresses issue #207.

Issue 207: Ignore all internal document properties

---

CHANGELOG.md
src/testing/validation-error-formatter.js
src/testing/validation-error-formatter.spec.js
templates/sync-function-validation-module.js

Brings some consistency to some of the outlier error messages (e.g. for attachment references, UUIDs, immutable items, required items, etc.).
Addresses issue #212.

Issue 212: Update various document validation error messages

---

CHANGELOG.md
README.md
src/testing/validation-error-formatter.js
src/testing/validation-error-formatter.spec.js
src/validation/document-definitions-validator.spec.js
src/validation/property-validator-schema.js
templates/sync-function-validation-module.js
test/resources/string-doc-definitions.js
test/string.spec.js

Adds a new constraint for the `string` validation type that, when enabled, ensures that a candidate value does not begin or end with whitespace.
Addresses issue #204.

Issue 204: String constraint that prohibits leading or trailing spaces

---

CHANGELOG.md
src/loading/file-fragment-loader.js
test/fragment.spec.js
test/resources/fragment-doc-definitions.js
test/resources/fragment-nested-property.js
test/resources/fragment-object-doc-definition.js

The import of file fragments (e.g. using the `importSyncFunctionFragment` or `importDocumentDefinitionFragment` macros) is far more versatile now that they can be nested an arbitrary number of levels deep in the file hierarchy rather than only at the top level.
Addresses issue #215.

Issue 215: Recursively import file fragments that are nested

---

CHANGELOG.md
src/validation/document-definitions-validator.spec.js
src/validation/property-validator-schema.js
templates/sync-function-validation-module.js
test/date.spec.js
test/resources/date-doc-definitions.js

Date strings now have the option to omit their month and day components. If a component is absent, its value is assumed to be "01" by convention (e.g. "2018-01" and "2018" are both the same date as "2018-01-01").
Addresses issue #197.

Issue 197: Month and day are now optional components of date-only strings

---

.jshintrc
.travis.yml
CHANGELOG.md
CONTRIBUTING.md
README.md
package.json

WARNING: Breaking change.
Updated the project's package configuration to indicate that only Node.js versions 8.9.0 or higher may be used. Technically earlier versions may work now and in the future, but they are not supported. Also increased the version of the ECMAScript specification that Node.js code supports from ES5 to ES2015/ES6.
Addresses issue #185 for the upcoming 2.0.0 release.

Issue 185: Set minimum supported Node.js version

---

CHANGELOG.md
templates/sync-function-validation-module.js
test/datetime.spec.js
test/resources/datetime-doc-definitions.js

Workaround to an issue in which the `date` and `datetime` range constraints mishandle dates after "2262-04-11T23:47:16.854Z" or before "1677-09-21T00:12:43.146Z" due to a bug in the `Date` constructor and `Date.parse`'s parser implementation for ISO 8601 date strings. Dates are now manually parsed from ISO 8601 string form and used to construct timestamps directly when performing range validation checks.
Addresses issue #203.

Issue 203: Manually parse ISO 8601 date strings for range validation

---

src/testing/test-environment-maker.js
src/testing/test-environment-maker.spec.js
src/validation/validation-environment-maker.js
src/validation/validation-environment-maker.spec.js

Previously the `test-environment-maker` and `validation-environment-maker` modules used a relative file path to reference their respective template files. However, this is invalid when the module is run from a dependent project since the current working directory will be the root of _that_ project rather than the root of synctos. Now it uses Node.js' built in `path` module to resolve the template file paths correctly.
Required for issue #230.

Issue 230: Fix file path resolution for test and validation environment templates

---

CHANGELOG.md
CONTRIBUTING.md
README.md
samples/sample-sync-doc-definitions.js
src/validation/property-validator-schema.js
templates/sync-function-validation-module.js
test/custom-validation.spec.js
test/resources/custom-validation-doc-definitions.js
test/resources/underscore-js-doc-definitions.js

Previously the wrong elements were passed as the fourth argument to a `customValidation` constraint function. Now the stack contains elements starting from the root (i.e. the document itself) up to but excluding the item under evaluation.
Addresses issue #98.

Issue #98: Pass correct values to final param of custom validation constraints

---

test/resources/string-doc-definitions.js
test/string.spec.js

Verifies that the inclusive and exclusive range constraints work as expected for the `string` validation type.
Addresses issue #235.

Issue 235: Minimum and maximum value constraint tests for strings

---

templates/.jshintrc
templates/sync-function/access-assignment-module.js
templates/sync-function/attachment-module.js
templates/sync-function/authorization-module.js
templates/sync-function/comparison-module.js
templates/sync-function/json-stringify-module.js
templates/sync-function/template.js
templates/sync-function/time-module.js
templates/sync-function/validation-module.js
templates/validation-environment-template.js

Introduces the attachment module, which is responsible for validation of attachment constraints and attachment references. Also took the liberty of refactoring how utility functions (e.g. `isValueNullOrUndefined`, `isDocumentMissingOrDeleted`, `simpleTypeFilter`) are accessed by the sync function template's various submodules (i.e. they are now passed via the `utils` parameter).
This should be the final pull request to address issue #217.

Issue 217: Extract attachment validation logic into its own module

---

src/testing/test-fixture-maker.js
src/testing/test-fixture-maker.spec.js
test/access-assignment.spec.js
test/attachment-constraints.spec.js
test/custom-actions.spec.js
test/general.spec.js
test/sample-notification-transport.spec.js

Ensures that the properties of a test fixture's test environment are the single source of truth for the Sync Gateway API function stubs by no longer exposing them directly through the test fixture object. Now they can only be accessed through a test fixture's `testEnvironment` property. This prevents cases where the test environment can get out of sync with the test fixture if the caller reassigns one of the properties in question (e.g. when `test-fixture-maker.spec.js` reassigns the `syncFunction` property).
This last bit of refactoring should be the final step to address issue #252.

Issue 252: Expose Sync Gateway API stubs via test environment

---

README.md
src/testing/validation-error-formatter.js
test/custom-validation.spec.js
test/datetime.spec.js
test/document-id-regex-pattern.spec.js
test/resources/document-id-regex-pattern-doc-definitions.js
test/resources/dynamic-constraints-doc-definitions.js

Includes several miscellaneous non-functional changes that don't necessarily merit creating their own issues/tickets:
- Removed debug `console.log` statement from `datetime` test case
- Switched to template strings instead of string concatenation in a couple of remaining cases in Node.js modules
- Replaced function blocks with simple expressions in validation-error-formatter module
- Included a link to the [couchster](https://github.com/OldSneerJaw/couchster) spinoff project in the README
- Avoided Sync Gateway admin UI [bug](https://github.com/Kashoo/synctos/issues/116) in test document definitions when a problematic character sequence (`$'`) is encountered
Executed the full test suite with `npm test`.
* GitHub issue link: N/A

Spring cleaning

---

CHANGELOG.md
package-lock.json
package.json

Locally updated [kashoo-document-definitions](https://github.com/Kashoo/kashoo-document-definitions) to target the version of synctos with a fix for issue #270. Executed several document writes using both Sync Gateway 1.5.1 and [2.0.0 beta 2](https://packages.couchbase.com/releases/couchbase-sync-gateway/2.0.0-beta2/couchbase-sync-gateway-enterprise_2.0.0-beta2_x86_64.tar.gz).
* GitHub issue link: #272

Issue 272: Release of 2.2.1

---

CONTRIBUTING.md

Added release procedure documentation to the contribution guidelines (`CONTRIBUTING.md`) file.
I have followed these steps for many past releases, though they are only just now being stored in the repo.
* GitHub issue link: #274

Issue #274: Release procedure documentation

---

CONTRIBUTING.md
etc/jshintrc-sync-function-template.json
src/testing/test-environment-maker.js
src/testing/test-fixture-maker.spec.js
src/testing/test-helper.js
src/testing/test-helper.spec.js
src/validation/validation-environment-maker.js
templates/environments/test-environment-template.js
templates/environments/validation-environment-template.js
templates/sync-function/.jshintrc
templates/sync-function/template.js
templates/sync-function/validation-module.js
test/custom-actions.spec.js
test/resources/custom-actions-doc-definitions.js

Eliminates reliance on the stubbed function (`customActionStub`) that was injected into every test environment to test the custom actions feature. The new approach is more precise about which custom action event was actually executed to generate each piece of metadata that is passed along.
Executed the full test suite with `npm test`.
* GitHub issue link: #279

Issue 279: Refactor custom action tests

---

src/loading/sync-function-loader.js
src/loading/sync-function-loader.spec.js
src/testing/test-environment-maker.js
src/testing/test-environment-maker.spec.js
src/testing/test-helper.spec.js
src/validation/validation-environment-maker.js
src/validation/validation-environment-maker.spec.js
templates/environments/.jshintrc
templates/environments/test-environment-template.js
templates/environments/validation-environment-template.js
templates/sync-function/.jshintrc
templates/sync-function/template.js

Changed `%SYNC_DOCUMENT_DEFINITIONS%`, `%SYNC_FUNC_PLACEHOLDER%` and `%DOC_DEFINITIONS_PLACEHOLDER%` to `$DOCUMENT_DEFINITIONS$`, `$SYNC_FUNC_PLACEHOLDER$` and `$DOC_DEFINITIONS_PLACEHOLDER$`, respectively. The new macro names are legal JavaScript names, so there are no longer JavaScript errors when editing the raw template files.
Ran the full test suite with `npm test`.
* GitHub issue link: N/A

Update template string macro names

---

CHANGELOG.md
templates/sync-function/authorization-module.js
templates/sync-function/template.js
templates/sync-function/validation-module.js

Throwing an Error object results in a more meaningful error message when there is an unexpected authorization or validation failure in a test case. Also, the result is functionally the same as throwing a plain object in a live instance of Sync Gateway.
In addition to running the full test suite with `npm test`, there were three main scenarios to be verified manually. In each case, I generated a sync function from `test/resources/authorization-doc-definitions.js` and pasted it into a Sync Gateway configuration file. Then I executed each scenario using Sync Gateway 1.5.1 and 2.0.0 beta 2 to ensure that the error details are still generated properly.
Submit the following request:
```
PUT /test/invalid-doc HTTP/1.1
Host: localhost:4985
Content-Type: application/json
{
"foo": "bar"
}
```
The …

Issue 285: Always throw an Error object to indicate invalid content or permissions

---

CHANGELOG.md
make-sync-function
src/index.js
src/index.spec.js
src/loading/sync-function-loader.js
src/loading/sync-function-loader.spec.js
src/saving/sync-function-writer.js
src/saving/sync-function-writer.spec.js
src/testing/test-environment-maker.js
src/testing/test-environment-maker.spec.js
src/testing/test-fixture-maker.js
src/testing/test-fixture-maker.spec.js
src/testing/test-helper.js
src/testing/test-helper.spec.js

The backtick character is no longer escaped when document definitions are read from the file system. Instead, backticks are escaped only at the time that the generated sync function is subsequently written to a file.
Ran the full test suite with `npm test`. Also applied a generated sync function to a Sync Gateway configuration file, both as a JavaScript block (i.e. by running `./make-sync-function test/resources/timezone-doc-definitions.js build/output.js`) and enclosed in a JSON string (i.e. by running `./make-sync-function -j test/resources/timezone-doc-definitions.js build/output.txt`) and then ensuring that I could create and replace documents without JavaScript errors.
* GitHub issue link: #288

Issue 288: Escape backticks only when writing a sync function to a file

---

src/environments/stubbed-environment-maker.js
src/environments/stubbed-environment-maker.spec.js
src/loading/sync-function-loader.js
src/loading/sync-function-loader.spec.js
src/testing/test-environment-maker.js
src/testing/test-environment-maker.spec.js
src/testing/test-fixture-maker.js
src/testing/test-fixture-maker.spec.js
src/validation/document-definitions-validator.js
src/validation/validation-environment-maker.js
src/validation/validation-environment-maker.spec.js
templates/sync-function/.jshintrc
templates/sync-function/template.js

Introduces a new `stubbed-environment-maker` module that is used by the existing `test-environment-maker` and `validation-environment-maker` modules to generate fake Sync Gateway environments for tests and schema validation, respectively.
Execute `npm test`.
* GitHub issue link: #289

Issue 289: Extract shared logic from test and validation environment makers

---

CHANGELOG.md
README.md
src/testing/validation-error-formatter.js
src/testing/validation-error-formatter.spec.js
src/validation/document-definitions-validator.spec.js
src/validation/property-validator-schema.js
templates/sync-function/document-properties-validation-module.js
test/resources/string-doc-definitions.js
test/string.spec.js

The new constraint (`mustEqualIgnoreCase`) operates like `mustEqual` except that it applies only to strings and it ignores differences in case.
Repeat for Sync Gateway 1.x and 2.x:
1. Generate a sync function from the string specification document definitions: `./make-sync-function -j test/resources/string-doc-definitions.js build/test-sync-function.json`
2. Copy and paste the sync function's contents into a Sync Gateway configuration file
3. Launch Sync Gateway with the configuration file
4. Attempt to create a document with a complete mismatch in values:
```
PUT /test/stringDoc HTTP/1.1
Host: localhost:4985
Content-Type: application/json
{
"dynamicCaseInsensitiveEqualityValue": "foo",
"dynamicMustEqualIgnoreCaseValidationProp": "bar"
}
```
The document should be rejected with the reason …

Issue 311: Constraint that matches against string value, ignoring case

---

CHANGELOG.md
README.md
src/testing/validation-error-formatter.js
src/testing/validation-error-formatter.spec.js
src/validation/document-definitions-validator.spec.js
src/validation/property-validator-schema.js
templates/sync-function/attachments-validation-module.js
test/attachment-constraints.spec.js
test/attachment-reference.spec.js
test/resources/attachment-constraints-doc-definitions.js
test/resources/attachment-reference-doc-definitions.js

When included in a document definition, the `attachmentReference` validation type's `regexPattern` constraint verifies that the value conforms to the specified regular expression pattern. It overrides the value of the document-wide `attachmentConstraints.filenameRegexPattern` constraint for that attachment reference.
First, verify that the constraint works on its own (i.e. without being forced to interact with `attachmentConstraints.filenameRegexPattern`):
1. Generate a sync function from `attachment-reference-doc-definitions.js`:
```bash
./make-sync-function -j test/resources/attachment-reference-doc-definitions.js build/test-sync-function.txt
```
2. Copy and paste the sync function into a Sync Gateway configuration file.
3. Attempt to create a test document with an attachment reference …

Issue 316: Regular expression pattern constraint for attachment references

---

CHANGELOG.md

Now that v2.5.0 has been released, the changelog's "Unreleased" section has been restored.
* GitHub issue link: #315

Issue 315: Restore the Unreleased section to the changelog

---

CHANGELOG.md
README.md
src/validation/document-definitions-validator.spec.js
src/validation/property-validator-schema.js
templates/sync-function/document-properties-validation-module.js
test/any-type.spec.js
test/resources/any-type-doc-definitions.js

A property or element with the `any` validation type can have a value from any of the standard JSON data types: number, string, boolean, array or object. As noted in the related issue, universal validation type constraints are supported by the `any` type, but type-specific constraints (e.g. `string`'s `mustBeTrimmed` constraint or `object`'s `allowUnknownProperties` constraint) are not.
Follow these instructions for both Sync Gateway 1.5.1 and 2.0.0:
1. Generate a sync function from `any-type-doc-definitions.js`:
```bash
./make-sync-function -j test/resources/any-type-doc-definitions.js build/test-sync-function.txt
```
2. Copy and paste the generated sync function into a Sync Gateway configuration file.
3. Create a valid `anyTypeDoc` document (should be accepted with 201 Created):
```
PUT …
```

Issue 324: Support for any JSON data type

---

CHANGELOG.md
README.md
samples/fragment-notification.js
samples/fragment-notifications-config.js
src/testing/validation-error-formatter.js
src/testing/validation-error-formatter.spec.js
src/validation/document-definitions-validator.spec.js
src/validation/property-validator-schema.js
templates/sync-function/document-properties-validation-module.js
test/conditional-validation.spec.js
test/resources/conditional-validation-doc-definitions.js
test/sample-notification.spec.js
test/sample-notifications-config.spec.js

The `conditional` validation type allows an item's value to conform to any one of several candidate validators. Each validator is accompanied by a condition that specifies whether to apply the validator to the item's value. If none of the conditions are satisfied, the value is rejected. This allows, for example, an array to contain a mix of data types or an object property to expect a different string format based on the state of other properties of the object.
Follow these instructions for both Sync Gateway 1.5.1 and 2.0.0:
1. Generate a sync function from `conditional-validation-doc-definitions.js`:
```bash
./make-sync-function -j test/resources/conditional-validation-doc-definitions.js build/test-sync-function.js
```
2. Copy and paste the generated sync function into a Sync Gateway …

Issue 86: Implementation of conditional validation type

---

CHANGELOG.md
CONTRIBUTING.md

* Restored the "Unreleased" section to the changelog
* Updated publishing instructions
Run `npm test`.
* GitHub issue link: #334

Issue 334: Post-release tasks for v2.7.0
