CHANGELOG.md

The final step before the release of 1.3.1.

Update change log for release of v1.3.1

---

CHANGELOG.md

This is the final step before the package is published to npm.

Update change log for release of v1.4.0

---

CHANGELOG.md

Typically this is the final step before publishing the new package version to npm.
Includes all previously unreleased features. The "Unreleased" section will be restored in another commit following the release.

Update change log for release of v1.7.0

---

CHANGELOG.md

Includes all previously unreleased additions and fixes. The "Unreleased" section of the change log will be restored in another commit following the release.

Update change log for release of v1.9.0

---

CHANGELOG.md

Includes all previously unreleased additions, changes and fixes. The "Unreleased" section of the change log will be restored in another commit following the release.

Update change log for release of v1.9.1

---

package-lock.json
package.json

Courtesy of Greenkeeper. Supersedes PR #171.

Update mock-require to version 3.0.1

---

CONTRIBUTING.md

The specifics of the project's new directory structure is now documented in `CONTRIBUTING.md`.
Concludes the implementation of issue #174.

Issue 174: Document directory structure in contribution guidelines file

---

CONTRIBUTING.md
README.md

Also updated contribution guidelines to mention the need to update the TOC whenever a new heading is added to the README.

Add table of contents to the README

---

package.json

Improves the package's visibility on npm.

Add description and keywords to package configuration

---

CHANGELOG.md
package-lock.json
package.json
src/testing/test-environment-maker.js
src/testing/test-environment-maker.spec.js
src/validation/validation-environment-maker.js
src/validation/validation-environment-maker.spec.js

Issue 230: Release of v2.0.0

---

CHANGELOG.md
CONTRIBUTING.md
README.md
package-lock.json
package.json
samples/sample-sync-doc-definitions.js
src/validation/property-validator-schema.js
templates/sync-function-validation-module.js
test/custom-validation.spec.js
test/resources/custom-validation-doc-definitions.js
test/resources/underscore-js-doc-definitions.js

Issue 237: Release of 2.0.1

---

templates/sync-function/comparison-module.js
templates/sync-function/validation-module.js

Introduces the comparison module, which is responsible for all things related to verifying minimum and maximum values, equality and item immutability.
This is the second of three pull requests to address issue #217.

Issue 217: Extract range, equality and immutability validation logic into a new module

---

CHANGELOG.md
package-lock.json
package.json

Issue 248: Release of 2.0.2

---

CHANGELOG.md
package-lock.json
package.json

Issue 253: Release of 2.1.0

---

CHANGELOG.md
README.md
package-lock.json
package.json

- Upgraded the [nyc](https://www.npmjs.com/package/nyc) development dependency to the latest version
- Tweaked badges in README
Validated the [release candidate](https://github.com/Kashoo/synctos/releases/tag/v2.2.0-rc.1) using the [kashoo-document-definitions](https://github.com/Kashoo/kashoo-document-definitions) repo.
* GitHub issue link: #267

Issue 267: Release of 2.2.0

---

CHANGELOG.md
package-lock.json
package.json

- Upgraded development dependencies
Locally updated [kashoo-document-definitions](https://github.com/Kashoo/kashoo-document-definitions) to the [release candidate](https://github.com/Kashoo/synctos/releases/tag/v2.3.0-rc.1) of 2.3.0. Executed several document writes using both Sync Gateway 1.5.1 and [2.0.0 Beta 2](https://packages.couchbase.com/releases/couchbase-sync-gateway/2.0.0-beta2/couchbase-sync-gateway-enterprise_2.0.0-beta2_x86_64.tar.gz).
* GitHub issue link: #298

Issue 298: Release tasks for v2.3.0

---

CHANGELOG.md
package-lock.json
package.json

- Upgraded development dependencies
Followed the testing instructions for pull request #304 to verify the document expiry feature.
Also, locally updated [kashoo-document-definitions](https://github.com/Kashoo/kashoo-document-definitions) to the [release candidate](https://github.com/Kashoo/synctos/releases/tag/v2.4.0-rc.1) of 2.4.0. Executed a number of document writes using both Sync Gateway 1.5.1 and 2.0.0.
* GitHub issue link: #306

Issue 306: Preparation for release of 2.4.0

---

CHANGELOG.md
lib/joi/joi.bundle.js

- Restored the "Unreleased" section to the changelog
- Upgraded the joi dependency to the most recent version
```bash
npm test
```
* GitHub issue link: #306

Issue 306: 2.4.0 post release tasks

---

CHANGELOG.md
CONTRIBUTING.md
package-lock.json
package.json

* Updated the changelog
* Updated the package version
* Tweaked the release branch naming guidelines in `CONTRIBUTING.md`
Execute the test cases from pull requests #333 and #339.
* GitHub issue link: #341

Issue 341: Prepare release of v2.7.1

---

CHANGELOG.md

* Restored the "Unreleased" section to the changelog
Run `npm test`.
* GitHub issue link: #341

Issue 341: Post-release tasks for v2.7.1
